### ISSUE TITLE
Managed Redis DB: Edit user privileges

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#296] opened 2022-09-11 23:16 UTC
As a Managed Database User, on Redis DB, i ould like to be able to edit a user privileges from OVH Manager UI.

Currently we cannot edit a user on I, in order for example to add a channel, to add a privilege etc...
We can only delete and create a new user, which force us to reset the password.

I would like to be able to adit that user without changing te password.

**Comment by thild42** [comment] 2023-03-23 09:37
Closing as duplicate of  #382

**Closed by thild42** 2023-03-23 09:37 UTC
