### ISSUE TITLE
OAuth for Managed Private Registry

### ISSUE THREAD

**Issue by pascal-sochacki** [ovh/public-cloud-roadmap#384] opened 2023-03-29 14:15 UTC
As a customer
I want to connect my Managed Private Registry with an OIDC single sign-on (SSO) provider
So that
I can manage my Users in one place.  

Currently, it seems like all Users must be created with the initial Admin User. I would appreciate it if I could connect the registry with an OIDC Provider (in my case, Keycloak) to manage users. 

The Harbor docs describe which steps need to be done (https://goharbor.io/docs/1.10/administration/configure-authentication/oidc-auth/). It is not possible to change the “Auth Mode” to oidc

**Comment by mhurtrel** [comment] 2023-03-30 07:49
Hello @pascal-sochacki I confirm this feature in planned, and this ticket is a duplicate of https://github.com/ovh/public-cloud-roadmap/issues/83

**Closed by mhurtrel** 2023-03-30 07:49 UTC

**Comment by mhurtrel** [comment] 2023-08-30 12:37
Hi @pascal-sochacki and @biapar Just wanted to let you know that the duplicate feature has now been released : https://github.com/ovh/public-cloud-roadmap/issues/83
