### ISSUE TITLE
Default private network gateway when using vrack in K8s

### ISSUE THREAD

**Issue by jMonsinjon** [ovh/public-cloud-roadmap#116] opened 2021-07-28 16:06 UTC
As a Managed Kubernetes Service user
I want my worker nodes to be deployed in one of my private networks
and the default output network gateway is my private network's one and not the public one.

I may have the choice during cluster creation to set the default gateway (public or private).

If the default gateway is the private one, worker nodes will still have a public network interface for OVHcloud's Managed K8s service management only.

**Comment by mhurtrel** [comment] 2021-08-03 13:46
Our colleague @LostInBrittany wrote a guide describing how to manually define routes to manage this advanced use case (Kubernetes cluster in a vRack private Network wanting to access to other private network in the same vRack) : https://docs.ovh.com/gb/en/kubernetes/vrack-example-between-private-networks/ . This will be useful before this default gateway feature is developed.

**Comment by mhurtrel** [comment] 2021-11-04 13:56
I juste learned that unfortunately, the feature is postoned another month to december. relaly sorry about those delays

**Comment by melbek** [comment] 2021-12-15 14:45
Hey @mhurtrel ,

is there an update on this topic? :)

**Comment by mhurtrel** [comment] 2021-12-15 15:10
@melbek feature is now posponed to january. sorry for our difficulties to commit to our ETA this quarter. we were impacted by many last minutes priorities that we could not anticipate

**Comment by nico-opp** [comment] 2021-12-16 07:59
@mhurtrel thanks for your feedback . We use static routes in vRack private network to our own gateway like described in your previous post  . works well.

**Comment by mhurtrel** [comment] 2022-01-06 09:31
Due to new unexpetcted delays, this should now be prodded in February

**Comment by golivhub** [comment] 2022-02-08 09:23
Hello, 

Any update about the date of the release please ?

**Comment by mhurtrel** [comment] 2022-03-09 11:39
Hello. Due to new unexpected multiple delays, our teams will be able to prod this feature in about 2 months.
I am deeply sorry for this huge delays due to major internal tools upgrades + covid impact that we could not anticipateand impacted greatly during multiple months. We are now getting close to finishing those major changes and should be able to focus again on these improvements.

**Comment by ducseb** [comment] 2022-05-17 11:40
Any news on this feature ?

**Comment by cambierr** [comment] 2022-05-19 09:22
Hi @mhurtrel / @LostInBrittany 

Is there any "clean" way (by clean, I mean without mounting host network in a pod to reconfigure the routing table) to change the host routing table so that all traffic goes through the vrack using its DHCP config to find the correct gateway ?

**Comment by jMonsinjon** [comment] 2022-05-31 13:34
> ts DHCP config to find the correct gateway ?

Hello, you can inject static routing rules with DHCP.

**Comment by bbaccot** [comment] 2022-06-17 13:31
Hello, do you confirm that this feature is now available through the API?
In which case, do you know where the documentation can be found?
Many thanks!

**Comment by jMonsinjon** [comment] 2022-06-18 00:09
Hello,
During this end of week, we were in trouble with our deployment stack.
We are a little bit late.
The Api will be opened early next week (Monday) and the documentation will be provided few days after.

We look forward to opening this new feature, and to getting your first feedback

**Comment by fred-cardoso** [comment] 2022-06-20 15:56
Hi @mhurtrel,

Thanks for the update.
I have a few questions about this feature though.

- Can we update an existing cluster? The API change appears to only allow the change on new cluster.
- As a "real-world" example; If the cluster is deployed using the `privateNetworkRoutingAsDefault` as `true`, will it still be externally accessed by the Internet? If my purpose is to make sure the K8S cluster access, for example, one VM inside my vRack will the external connectivity to the cluster keep working?
- I'm I safe to assume that if the cluster is using the vRack gateway, any outbound traffic required will go through the nodes external interfaces?

I'm sorry if I missed something.

Thank you!

**Comment by alesqueren** [comment] 2022-07-07 09:31
Hi everyone,

We are very excited about this new feature. 
It will fix many problems we have.

Unfortunately, i tried to set the `privateNetworkRoutingAsDefault` via the OVHcould API but I can't make it work.

```
POST /1.0/cloud/project/$ServiceName/kube
{
  "name": "dev_tmp",
  "nodepool": {
    "antiAffinity": false,
    "autoscale": true,
    "desiredNodes": 1,
    "flavorName": "d2-8",
    "maxNodes": 3,
    "minNodes": 1,
    "monthlyBilled": false
  },
  "privateNetworkConfiguration": {
    "privateNetworkRoutingAsDefault": true
  },
  "privateNetworkId": "$PrivateNetworkID",
  "region": "SBG5",
  "version": "1.23"
}
```
```
HTTP/1.1 400 Bad Request
{
  "class": "Client::BadRequest",
  "message": "[InvalidDataError] 400: Private network $PrivateNetworkID does not exist (request ID: 266a1404-f1e3-43ef-ade1-e2db313853eb)"
}
```

The private network is displayed on the OVH UI and I can get it with the OVHcloud API:
```
GET /1.0/cloud/project/$ServiceName/network/private 
```
```
HTTP/1.1 200 OK
[
  {
    "id": "$PrivateNetworkID",
    "name": "VLAN_TMP",
    "vlanId": 2,
...
```

Did I missed something ?

Thank you

**Comment by matprig** [comment] 2022-07-07 09:57
Hello,
For the range 172.16.0.0/12 it depends of the docker configuration and it differs following literature for example:
https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-8/cortex-xsoar-admin/docker/docker-hardening-guide/docker-network-hardening

best,

**Comment by XavierDuthil** [comment] 2022-07-07 10:23
Hello @alesqueren, the private network ID corresponds to the `openstackId` field in the call you mentioned, it is associated to a specific region:

```
GET /1.0/cloud/project/$ServiceName/network/private 
HTTP/1.1 200 OK
[
  {
    id: "pn-XXXXXXX_Y",
    name: "my-vrack",
    vlanId: 2,
    regions: [
      {
        region: "GRA7"
        status: "ACTIVE"
        openstackId: "$PrivateNetworkID"
      },
```

Though I admit that this can be confusing. We will try to make it clearer or easier to use.

**Comment by alesqueren** [comment] 2022-07-07 12:24
Thank you @XavierDuthil @matprig, I managed to create the cluster with your advices :-)

Unfortunately, kubernetes nodes does not have access to internet.

When creating a pod:
```
│ Events:
│   Type     Reason     Age   From               Message
│   ----     ------     ----  ----               -------
│   Normal   Scheduled  21s   default-scheduler  Successfully assigned default/tmp-shell2 to nodepool-node-628f8e
│   Normal   Pulling    20s   kubelet            Pulling image "ubuntu"
│   Warning  Failed     3s    kubelet            Failed to pull image "ubuntu": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/ubuntu:latest": failed to resolve reference "docker.io/library/ubuntu:latest": failed to do request: Head https://registry-1.docker.io/v2/library/ubuntu/manifests/latest: dial tcp 44.207.96.114:443: connect: no route to host
│   Warning  Failed     3s    kubelet            Error: ErrImagePull
```

When curling google from an existing pod:
```
 <<K9s-Shell>> Pod: kube-system/metrics-server-568d645498-hbgk2 | Container: metrics-server 
I have no name!@metrics-server-568d645498-hbgk2:/opt/bitnami/metrics-server$ curl google.com
curl: (7) Failed to connect to google.com port 80: No route to host
```

I would like to use the 2nd use case: 
_You set privateNetworkRoutingAsDefault as true but do not specify defaultVrackGateway : the routing will use the gateway provided by Openstack private network DHCP._
![Sélection_025](https://user-images.githubusercontent.com/30521840/177772010-c54896ae-38f7-4d82-a0f1-97e8510c93c5.png)
![Sélection_024](https://user-images.githubusercontent.com/30521840/177772016-cb65f40c-dfbf-4969-9be4-0a2f97ade07b.png)

Any idea is welcomed :-)

**Comment by matprig** [comment] 2022-07-07 13:23
hello,

You have checked the "activer la passerelle par défaut" this does not create a gateway, this allow to configure the network interface routing through DHCP automatically. The value is the first IP of the CIDR you gave to your network which is "burnt".

You have to create a gateway by creating an instance which has a public interface and a private interface into your private subnet 
`#!/bin/bash

echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
sysctl -p
iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
iptables-save > /etc/iptables_rules.save
`
or you can try a virtual router https://labs.ovh.com/public-cloud-l3-services which is beta but i dont yet use it.

best,

**Comment by mhurtrel** [comment] 2022-07-18 08:36
![image](https://user-images.githubusercontent.com/24432524/179474066-4050d3ee-cf6c-4432-9f97-b608bdb4232d.png)

The gateway management for Kubernetes in vRack is now made available in the manager (both at cluster creation and reset).
Note that changing the gateway during cluster lifetime is currently only possible through API.

Documentation of the feature should be released this week by the great  !

**Comment by jgermond** [comment] 2022-07-25 09:47
Hello, 

I tried to create a private network to have the same fixed outgoing IP for all my nodes.
I reset my cluster with the private network and set the gateway IP in the same network.

![image](https://user-images.githubusercontent.com/7223093/180746398-59878c9b-3ea5-40ff-9c58-add2764f6b5e.png)

All my nodes have an internal IP in the private network.
But my nodes are still going out with their external/public IP instead of the gateway.
When I run `curl ifconfig.me`, the service detects the public IP instead of the gateway IP.

What am i doing wrong?
Or is this a bug?

**Comment by jgermond** [comment] 2022-07-25 14:09
I also notice that my k8s service (LoadBalancer type) fails its creation when the cluster is in a private network, because of a code 500 error:
`(combined from similar events): Error updating load balancer with new hosts map[permanent-node-3ded07:{}]: 500 Internal Server Error(EU.ext-5.62dea09c.24112.11381658-2e41-4a73-ae20-2ebe8593d549) - https://api.ovh.com/1.0/cloud/project/.../loadbalancer/.../configuration/1/apply: {"class":"Server::InternalServerError","message":"Internal server error"}`


Did I misunderstand something?
Or is this also a bug ?
I don't know if I should create a ticket in the help center or stay here.

**Comment by mhurtrel** [comment] 2022-07-26 07:25
Hi @jgermond please open a support ticket,.
Full documentation is about to be released for this feature, which has just been released in the web control pannel ( aka "manager")

**Comment by mhurtrel** [comment] 2022-07-26 14:54
The documentation is now available : https://docs.ovh.com/gb/en/kubernetes/vrack-k8s-custom-gateway/ and the feature is completed

**Closed by mhurtrel** 2022-07-26 14:54 UTC
Labels: functionnal and UX, Managed Kubernetes Service

**Comment by jgermond** [comment] 2022-07-28 08:38
Where can I give feedback on this documentation?
I found some errors.

**Comment by lenglet-k** [comment] 2022-08-18 13:49
Hello,

I don't understand for why your forbid `172.16.0.0/12`, it's very large CIDR. And in this `[documentation](https://docs.ovh.com/us/en/kubernetes/known-limits/#known-not-compliant-ip-ranges)` you block 172.17.0.0/16. We have 3 private MKS in 172.16.0.0/24 network  andtoday for have this private routing feature we have to recreate all ressources, network, K8S node, etc...

**Comment by matprig** [comment] 2022-08-23 13:19
Hello,

We have modified the forbidden range to 172.17.0.0/16. Indeed /12 was too restrictive.

best,

**Comment by benjamin-texier** [comment] 2022-09-01 16:01
Hello,

I have several problems following your documentation: https://github.com/ovh/docs/blob/develop/pages/platform/kubernetes-k8s/vrack-k8s-custom-gateway/guide.en-gb.md

Router creation seems to be possible only on `GRA11` and `GRA9`. But it is impossible to make private network only in `GRA7`.

```bash
utils/ovhAPI.sh POST /cloud/project/$OS_TENANT_ID/network/private "$(cat tpl/private_network.json)"
{"class":"Client::BadRequest","message":"Invalid region GRA9"}%
```

with `tpl/private_network.json`
```json
{
"name": "private-network",
"vlanId": 2,
"regions": ["GRA9"]
}
```

And this seems to be confirmed on the WEB part:

![image](https://user-images.githubusercontent.com/48748248/187958730-35341979-b2ff-4bdc-a398-8fd4e35d0f1e.png)

Assuming that there is a region error in the documentation, I tried with `GRA7`. But then, there is an error when creating the router:

```console
ResourceNotFound: 404: Client Error for url: https://network.compute.gra7.cloud.ovh.net/v2.0/routers, The resource could not be found.
```

Is there a problem on my side? Did I miss a step in the documentation?

Thanks,

**Comment by thomas-aw** [comment] 2023-05-16 17:06
In the help guide, the DHCP is false. Could you tell me why ?
Thanks
