### ISSUE TITLE
MKS nodepool spec 'desiredNodes' should be optional

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#267] opened 2022-07-08 14:28 UTC
As a MKS user, i would like nodepool spec 'desiredNodes' to be optional.

Because in case of AutoScaling nodepool, each time i am doing a deployment, i need to specify a 'desiredNodes' values.
So by default my value is 1 (or the same as minNodes).
But in case of peak of activity on my cluster, nodepool desiredNodes could be high, i do not want to reset it to its default value when performing `kubectl apply -f nodepool.yml`.

So this parameter should be optional.
In case the value is missing on creation of the nodepool, the value should be set to the same as 'minNodes' value.
In case the nodepool is already created, the current value should not be changed.

**Comment by matmicro** [comment] 2022-07-11 19:58
@mhurtrel do you think this could be easily and quickly delivered ?

**Comment by mhurtrel** [comment] 2022-07-12 13:00
Hi @matmicro I agree with your point and discussed with the team. We will amend this, but I can't give you and ETA yet.

**Comment by jMonsinjon** [comment] 2022-08-04 13:18
We implemented a behavior like this:

If desired_nodes parameter is empty AND a desired_nodes value already exists --> we use the existing value
If desired_nodes parameter is empty AND a there is no existing value --> we use min_nodes value
If desired_nodes parameter is specified AND desired_nodes parameter is lower than min_nodes --> we use min_nodes value
If desired_nodes parameter is specified AND desired_nodes parameter is upper than max_nodes --> we use max_nodes value
If desired_nodes parameter is specified AND between min_nodes and max_nodes --> we use the desired_nodes parameter value

**Comment by matmicro** [comment] 2022-08-04 15:12
@jMonsinjon Great, that's perfect !
Thanks for such quickfix !

Could you please let me know once this will be live on GRA5 ? and others regions ?
I am currently facing error : ``ValidationError(NodePool.spec): missing required field "desiredNodes" in com.ovh.cloud.kube.v1alpha1.NodePool.spec``

**Comment by jMonsinjon** [comment] 2022-08-04 15:47
OK sorry I reopened it.
The Kubernetes custom resource definition is not yet up to date.

I will close this issue as soon as it has been done.
It's our next priority ;-)

**Comment by matmicro** [comment] 2022-08-04 17:15
Can you share an ETA ? Thx

**Comment by jMonsinjon** [comment] 2022-08-11 13:53
@matmicro 
We are currently working on it and we will deploy it as soon as possible.
ETA: end of this week

**Comment by jMonsinjon** [comment] 2022-08-17 09:07
The feature has been released and we upgraded all nodepools controllers.
You can now use the OVHcloud API or your nodepool's custom ressource.

**Closed by jMonsinjon** 2022-08-17 09:07 UTC
Labels: functionnal and UX, Managed Kubernetes Service

**Comment by matmicro** [comment] 2022-08-18 19:11
It was working fine with Kubernetes 1.23 on GRA5.

But today it is not working with Kubernetes 1.24 on SBG5 :
error: error validating "k8s/nodepool_dev.yml": error validating data: ValidationError(NodePool.spec): missing required field "desiredNodes" in com.ovh.cloud.kube.v1alpha1.NodePool.spec;

Is it related to SBG or to Kubernetes version 1.24 ?

Could you fix this asap ?

**Comment by jMonsinjon** [comment] 2022-08-19 07:19
Hello @matmicro 
Checking right now....

**Comment by matprig** [comment] 2022-08-19 08:04
Hello @matmicro,

The issue is link to nodepool CRD deployment for kubernetes 1.24 which does not contain yet the change.

best,

**Comment by matmicro** [comment] 2022-08-19 08:05
Ok. Can you provide an ETA when this will be availabled with 1.24 ?
Thanks

**Comment by matprig** [comment] 2022-08-19 11:05
This is for ASAP, we have the fix, we have to run all test before release it

best,

**Comment by matprig** [comment] 2022-08-19 14:44
hello @matmicro 

we have just release the fix, you have to create a new cluster in 1.24 and it shall be ok

best,

**Comment by matmicro** [comment] 2022-08-19 15:00
Hi,
I can't create a new cluster, i need to use a current one.
I cannot plan to reset it on PROD, but i can for DEV/TEST purpose.

- What about reset the current cluster to 1.24 ? Fix will works ?
- And does it will work also when patching  a cluster 1.23 to upgrade to 1.24 ?

**Comment by matprig** [comment] 2022-08-19 15:52
Hi,

I can force a redeploy for you, can you give me your cluster id ?

- yes reset a cluster will work but you will loose all your data
- yes upgrading from 1.23 to 1.24 will work

**Comment by matprig** [comment] 2022-08-19 16:00
hi,

Redeploy was done in fact for you and the others, you can test now it shall work.

best

**Comment by matmicro** [comment] 2022-08-19 16:51
That's OK i could do it by myself with reset & upgrade.
All is fine now, thanks
