### ISSUE TITLE
Poland (WAW1) region

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#32] opened 2020-11-17 09:16 UTC
Making the Data Processing Service available in our Polish Datacenter.

Notes/Existing workaround :
The featureset and pricing model will be the same as existing regions.
Polish customer can already benefit from the service in other regions.

**Comment by thild42** [comment] 2023-06-29 07:14
Closed as duplicate of #388.

**Closed** 2023-06-29 07:16 UTC
Labels: Geo, Data Processing
