### ISSUE TITLE
HTTP3 (UDP) support on loadbalancers

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#354] opened 2023-02-21 11:04 UTC
As a MKS user i would like to be able to expose my services on HTTP3.
Currently this is not possible, facing the below issue on loadbalancer service :
`Error syncing load balancer: failed to ensure load balancer: only TCP protocol is supported, got: "UDP"`

Will this be available with Octavia loadbalancers ?

**Comment by yomovh** [comment] 2023-06-27 09:16
I propose to close this issue since it seems to be a duplicate of #416  (or the other way around ;-) )

**Closed by yomovh** 2023-06-27 09:16 UTC
